project_id = "anwqprmpzmcqbkttmxos"

[functions.fetch-podcast-feed]
verify_jwt = false

[functions.send-provider-notification]
verify_jwt = false

[functions.paypal-subscriptions]
verify_jwt = true

[functions.create-zoom-meeting]
verify_jwt = true

[functions.add-to-mailchimp]
verify_jwt = true