project_id = "anwqprmpzmcqbkttmxos"

[functions.fetch-podcast-feed]
verify_jwt = false

[functions.send-provider-notification]
verify_jwt = false

[functions.paypal-subscriptions]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.create-zoom-meeting]
verify_jwt = true

[functions.add-to-mailchimp]
verify_jwt = true

[functions.add-to-webinar-list]
verify_jwt = true

[functions.send-content-report]
verify_jwt = true

[functions.paypal-admin-sync]
verify_jwt = true

[functions.send-monthly-provider-analytics]
verify_jwt = false

[functions.send-zoom-registration-email]
verify_jwt = false

[functions.process-consultation-booking]
verify_jwt = false

[functions.generate-zoom-signature]
verify_jwt = false

[functions.auto-create-monday-zoom]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.send-member-zoom-reminder]
verify_jwt = false

[functions.resend-zoom-links]
verify_jwt = false

[functions.quo-to-notion]
verify_jwt = false
[functions.roadmap-mailchimp-sync]
verify_jwt = false

[functions.send-free-membership-email]
verify_jwt = true
